In [17]:
## 모듈 로딩
import numpy as np

In [18]:
## ndarray 타입 데이터 생성

# 0으로 채워진 ndarray 객체 생성 ==> zeros()
np.zeros(2)

array([0., 0.])

In [19]:
np.zeros((2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [20]:
# 1로 채워진 ndarray 생성 ==> ones()
np.ones(10), np.ones(10, dtype=np.int32), np.ones((2,5), dtype=np.bool_)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [21]:
# 랜덤 데이터로 ndarray 객체 생성 ==> random
np.random.randint(1,5,(3,10))

array([[2, 2, 1, 1, 3, 3, 2, 2, 3, 4],
       [2, 1, 1, 2, 3, 4, 4, 2, 1, 4],
       [4, 3, 4, 3, 3, 1, 2, 2, 1, 3]])

In [22]:
# 0<= 범위 <1
np.random.rand(10)

array([0.50183557, 0.11720756, 0.30532238, 0.17674592, 0.1106655 ,
       0.82927599, 0.11927202, 0.14875619, 0.71849101, 0.385607  ])

In [23]:
np.random.randn(5), np.random.randn(1,2,3)

(array([-0.17451591,  0.07863354, -0.96042648, -1.11401816, -0.85843776]),
 array([[[ 0.01288836,  1.14833778, -1.3336461 ],
         [ 0.30929194,  0.38687745,  1.53539596]]]))

In [31]:
data = np.random.randn(10)
print(data)

data = np.random.shuffle(data)
print(data)

[-0.01846553 -0.1727418  -0.64316186  0.53796237 -0.59121382 -0.09365338
  0.24467509  0.52189271  0.18986746 -0.18622409]
None


In [25]:
data.sum(), data.max(), data.min()

(2.2026235155107243, 1.7719894813379213, -0.9102573922448852)

In [28]:
data.argmax(), data.argmin(), data.mean()

(1, 5, 0.22026235155107243)