In [1]:
import cv2
img = cv2.imread('../img/blank_500.jpg')
type(img)

numpy.ndarray

In [2]:
img.ndim

3

In [3]:
img.shape

(500, 500, 3)

In [4]:
img.size

750000

In [5]:
img.dtype

dtype('uint8')

In [6]:
img.itemsize

1

In [7]:
import numpy as np
a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a.dtype

dtype('int64')

In [9]:
a.shape

(4,)

In [10]:
b = np.array([[1,2,3,4], [5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([1,2,3.14,4])
c

array([1.  , 2.  , 3.14, 4.  ])

In [13]:
c.dtype

dtype('float64')

In [14]:
d = np.array([1,2,3,4], dtype=np.float32)
d

array([1., 2., 3., 4.], dtype=float32)

# ????

In [15]:
a = np.uint8([1,2,3,4])
a

array([1, 2, 3, 4], dtype=uint8)

# ????

In [16]:
a = np.empty((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a.dtype

dtype('float64')

In [18]:
a.fill(255)
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [19]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
b.dtype

dtype('float64')

In [21]:
c=np.zeros((2,3), dtype=np.int8)
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [22]:
d = np.ones((2,3), dtype=np.int16)
d

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

# ???

In [23]:
e=np.full((2,3,4),255, dtype=np.uint8)
e

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]], dtype=uint8)

In [24]:
img = cv2.imread('../img/girl.jpg')
img

array([[[ 54,  70,  76],
        [ 48,  67,  70],
        [ 41,  68,  65],
        ...,
        [ 24,  72,  54],
        [ 31,  76,  59],
        [ 35,  80,  63]],

       [[ 53,  69,  75],
        [ 47,  68,  70],
        [ 41,  68,  64],
        ...,
        [ 26,  74,  56],
        [ 32,  77,  60],
        [ 35,  80,  63]],

       [[ 53,  69,  75],
        [ 46,  67,  68],
        [ 39,  69,  64],
        ...,
        [ 28,  76,  58],
        [ 31,  79,  61],
        [ 35,  80,  63]],

       ...,

       [[ 29,  94,  68],
        [ 38, 104,  75],
        [ 47, 115,  84],
        ...,
        [218, 190, 203],
        [219, 192, 202],
        [222, 192, 203]],

       [[ 28,  94,  65],
        [ 37, 104,  75],
        [ 47, 117,  86],
        ...,
        [218, 190, 203],
        [222, 192, 203],
        [224, 194, 205]],

       [[ 25,  92,  63],
        [ 36, 103,  74],
        [ 46, 116,  85],
        ...,
        [223, 193, 206],
        [226, 196, 207],
        [229, 199, 210]]

In [25]:
img.shape

(293, 406, 3)

In [26]:
a = np.empty_like(img)
b = np.zeros_like(img)
c = np.ones_like(img)
d = np.full_like(img, 255)

In [27]:
a, a.shape

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 (293, 406, 3))

In [28]:
b, b.shape

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 (293, 406, 3))

In [29]:
c, c.shape

(array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        ...,
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=uint8),
 (293, 406, 3))

In [30]:
d, d.shape

(array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
  

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
a.dtype

dtype('int64')

In [33]:
a.shape

(5,)

In [34]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [35]:
b.dtype

dtype('float64')

In [36]:
c = np.arange(3,9,2)
c

array([3, 5, 7])

In [37]:
np.random.rand()

0.20909266802333826

In [38]:
np.random.randn()

0.9061891509125369

In [39]:
a = np.random.rand(2,3)
a

array([[0.38648027, 0.90043368, 0.00920246],
       [0.52317519, 0.48898595, 0.49573288]])

In [40]:
b = np.random.randn(2,3)
b

array([[ 1.09024685, -1.2874287 , -0.2288267 ],
       [-0.01845565,  0.50426408,  0.68620999]])

In [41]:
a.dtype

dtype('float64')

In [42]:
c=a.astype(np.float64)
c

array([[0.38648027, 0.90043368, 0.00920246],
       [0.52317519, 0.48898595, 0.49573288]])

In [43]:
c.dtype

dtype('float64')

In [44]:
a.dtype

dtype('float64')

# ????

In [45]:
d= np.uint8(a)
d

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [46]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [47]:
b=a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
c=np.reshape(a,(2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
d=np.arange(100).reshape(2,-1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [50]:
d.shape

(2, 50)

In [51]:
e=np.arange(100).reshape(-1,5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [52]:
e.shape

(20, 5)

In [53]:
f=np.zeros((2,3))
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
f.reshape((6,))

array([0., 0., 0., 0., 0., 0.])

In [55]:
f.reshape(-1)

array([0., 0., 0., 0., 0., 0.])

In [56]:
np.ravel(f)

array([0., 0., 0., 0., 0., 0.])

In [57]:
g=np.arange(10).reshape(2,-1)
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
g.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [59]:
mylist = list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
for i in range(len(mylist)):
    mylist[i] = mylist[i] +1
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [61]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [64]:
a+5

array([5, 6, 7, 8, 9])

In [65]:
a-2

array([-2, -1,  0,  1,  2])

In [66]:
a*2

array([0, 2, 4, 6, 8])

In [67]:
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [68]:
a**2

array([ 0,  1,  4,  9, 16])

In [69]:
b=np.arange(6).reshape(2,-1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
b*2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [71]:
a

array([0, 1, 2, 3, 4])

In [72]:
a>2

array([False, False, False,  True,  True])

In [73]:
a=np.arange(10,60,10)
b=np.arange(1,6)
a

array([10, 20, 30, 40, 50])

In [74]:
b

array([1, 2, 3, 4, 5])

In [75]:
a+b

array([11, 22, 33, 44, 55])

In [76]:
a-b

array([ 9, 18, 27, 36, 45])

In [77]:
a*b

array([ 10,  40,  90, 160, 250])

In [78]:
a/b

array([10., 10., 10., 10., 10.])

In [79]:
a**b

array([       10,       400,     27000,   2560000, 312500000])

In [80]:
a=np.ones((2,3))
b=np.ones((3,2))
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
c=np.arange(3)
c

array([0, 1, 2])

In [ ]:
a+c

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
d=np.arange(2)
a+d

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
d=np.arange(2).reshape(2,1)
d

array([[0],
       [1]])

In [ ]:
a+d

array([[1., 1., 1.],
       [2., 2., 2.]])

In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1]

array([4, 5, 6, 7])

In [ ]:
b[1,2]

6

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[5]=9

In [ ]:
a

array([0, 1, 2, 3, 4, 9, 6, 7, 8, 9])

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0] =0
b

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1,2] = 99
b

array([[ 0,  0,  0,  0],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:5]

array([2, 3, 4])

In [ ]:
a[5:]

array([5, 6, 7, 8, 9])

In [ ]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0:2,1]

array([1, 5])

In [ ]:
b[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [ ]:
b[2,:]

array([ 8,  9, 10, 11])

In [ ]:
b[:,1]

array([1, 5, 9])

In [ ]:
b[0:2,1:3]=0
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [ ]:
bb= b[0:2,1:3]
bb

array([[0, 0],
       [0, 0]])

In [ ]:
bb[0]=99

In [ ]:
b

array([[ 0, 99, 99,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a[[1,3]]

array([1, 3])

In [ ]:
a[[True, False, True, False, True]]

array([0, 2, 4])

In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=a>5
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
a[b]

array([6, 7, 8, 9])

In [ ]:
a[a>5]

array([6, 7, 8, 9])

In [ ]:
a[a>5]=1

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [ ]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [ ]:
b[[0,2],[2,3]]

array([ 2, 11])

In [ ]:
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [ ]:
b=np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [ ]:
np.concatenate((a,b),1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [ ]:
a=np.arange(12).reshape(4,3)
b=np.arange(10,130,10).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
c=np.stack((a,b),0)
c.shape

(2, 4, 3)

In [ ]:
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [ ]:
d=np.stack((a,b),1)
d.shape

(4, 2, 3)

In [ ]:
d

array([[[  0,   1,   2],
        [ 10,  20,  30]],

       [[  3,   4,   5],
        [ 40,  50,  60]],

       [[  6,   7,   8],
        [ 70,  80,  90]],

       [[  9,  10,  11],
        [100, 110, 120]]])

In [ ]:
e=np.stack((a,b),2)
e.shape

(4, 3, 2)

In [ ]:
e

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [ ]:
ee=np.stack((a,b),-1)
ee.shape

(4, 3, 2)

In [ ]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.hsplit(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [ ]:
np.hsplit(a,[3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [ ]:
np.hsplit(a,[3,6,9])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [ ]:
np.split(a,3,0)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [ ]:
np.split(a,[3,6,9,],0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [ ]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.vsplit(b,2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [ ]:
np.split(b,2,0)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [ ]:
np.hsplit(b,[1])

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [ ]:
np.split(b,[1],1)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [ ]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.where(a>15)

(array([6, 7, 8, 9]),)

In [ ]:
np.where(a>15,1,0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [ ]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.where(a>15,99,a)

array([10, 11, 12, 13, 14, 15, 99, 99, 99, 99])

In [ ]:
np.where(a>15,99,a)

array([10, 11, 12, 13, 14, 15, 99, 99, 99, 99])

In [ ]:
np.where(a>15,a,0)

array([ 0,  0,  0,  0,  0,  0, 16, 17, 18, 19])

In [ ]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
coords=np.where(b>6)
coords

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [ ]:
np.stack((coords[0],coords[1]),-1)

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]])

In [ ]:
z=np.array([0,1,2,0,1,2])
np.nonzero(z)

(array([1, 2, 4, 5]),)

In [ ]:
zz=np.array([[0,1,2],[1,2,0],[2,0,1]])
zz

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [ ]:
coords =np.nonzero(zz)
coords

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 0, 2]))

In [ ]:
np.stack((coords[0],coords[1]),-1)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]])

In [ ]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.nonzero(a>15)

(array([6, 7, 8, 9]),)

In [ ]:
np.where(a>15)

(array([6, 7, 8, 9]),)

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.nonzero(b>6)

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [ ]:
np.where(b>6)

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [ ]:
t=np.array([True,True,True])
np.all(t)

True

In [ ]:
t[1]=False
t

array([ True, False,  True])

In [ ]:
np.all(t)

False

In [ ]:
tt=np.array([[True,True],[False,True],[True,True]])
tt

array([[ True,  True],
       [False,  True],
       [ True,  True]])

In [ ]:
np.all(tt,0)

array([False,  True])

In [ ]:
np.all(tt,1)

array([ True, False,  True])

In [ ]:
a=np.arange(10)
b=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
np.all(a==b)

True

In [ ]:
b[5]=-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

In [ ]:
np.all(a==b)

False

In [ ]:
np.where(a==b)

(array([0, 1, 2, 3, 4, 6, 7, 8, 9]),)

In [ ]:
np.where(a!=b)

(array([5]),)

In [ ]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a)

66

In [ ]:
np.sum(a,0)

array([12, 15, 18, 21])

In [ ]:
np.sum(a,1)

array([ 6, 22, 38])

In [ ]:
np.mean(a)

5.5

In [ ]:
np.mean(a,0)

array([4., 5., 6., 7.])

In [ ]:
np.mean(a,1)

array([1.5, 5.5, 9.5])

In [ ]:
np.amin(a)

0

In [ ]:
np.amin(a,0)

array([0, 1, 2, 3])

In [ ]:
np.amin(a,1)

array([0, 4, 8])

In [ ]:
np.amax(a)

11

In [ ]:
np.amax(a,0)

array([ 8,  9, 10, 11])

In [ ]:
np.amax(a,1)

array([ 3,  7, 11])

In [ ]:
import cv2

In [81]:
img = np.zeros((120,120),dtype=np.uint8)
img[25:35,:]=45
img[55:65,:]=115
img[85:95,:]=160
img[:,35:45]=205
img[:,75:85]=255
cv2.imshow('Gray',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

In [82]:
img = np.zeros((120,120,3),dtype=np.uint8)
img[25:35,:]=[255,0,0]
img[55:65,:]=[0,255,0]
img[85:95,:]=[0,0,255]
img[:,35:45]=[255,255,0]
img[:,75:85]=[255,0,255]
cv2.imshow('BGR',img)
cv2.waitKey(0)
cv2.destroyAllWindows()