In [131]:
import torch

1. 화면상에서 Pytorch에서 데이터를 저장하는 단위는 (  )입니다.

tensor

2. 1번 문제에 해당하는 것의 특징을 간력히 설명해 보세요.

연산이 빠름

3. Pytorch에서 정수형 데이터를 저장하는 데이터 타입을 모두 나열하세요.
간단한 데이터 타입의 크기 설명도 함께 작성하세요.

IntTensor

4. Pytorch에 논리형 데이터로 저장 후 속성을 출력하는 코드를 작성하세요.
데이터 : 10 -5 1.4 7 0 -1 0

In [132]:
a1 = torch.dtype=bool(10)
a2 = torch.dtype=bool(-5)
a3 = torch.dtype=bool(1.4)
a4 = torch.dtype=bool(7)
a5 = torch.dtype=bool(0)
a6 = torch.dtype=bool(-1)
a7 = torch.dtype=bool(0)

type(a1), type(a2), type(a3), type(a4), type(a5), type(a6), type(a7)

(bool, bool, bool, bool, bool, bool, bool)

5. 10개의 0 데이터를 2차원으로 저장 코드를 작성하세요.

In [133]:
b1 = torch.zeros(2,5)
b1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

6. 5개의 1 데이터가 대각선으로 저장되는 2차원 저장 코드를 작성하세요.

In [134]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

7. 5번에서 저장된 형태와 동일하지만 값이 3이 저장된 코드를 작성하세요.

In [135]:
torch.full_like(b1, 3)

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

8. ndarray데이터를 Pytorch에 저장하는 코드를 작성하세요.
데이터 : 1 ~ 100 범위에서 7의 배수
데이터 타입 : float32
생서 방식 : 공유

In [155]:
torch.randint(1, 100, (5,2))

tensor([[30, 94],
        [58, 87],
        [75, 59],
        [ 5, 63],
        [24, 32]])

In [ ]:
# 8. ndarray데이터를 Pytorch에 저장하는 코드를 작성하세요.(dtype = float32)
import numpy as np
array1 = np.arange(1, 101, 7)
data8 = torch.as_tensor(array1, dtype=torch.float32)
# data8 = torch.from_numpy(array1) # from_numpy는 dtype은 못 받음
data8, data8.dtype

9. 아래 조건에 맞는 데이터를 Pytorch에 저장하는 코드를 작성하세요.
이미지 파일 : flower.jpg 파일
이미지 크기 : 120 x 80
데이터 타입 : int8
데이터 : 임의의 값

#### tensor는 세로, 가로 순으로 들어가므로 80x120으로 만들거나 120x80.T해야
randint(0,255)

10. 아래 조건에 맞도록 코드를 작성하세요.
데이터 : 임의의 정수 10개
(1) 1D으로 저장
(2) (1)에서 저장된 데이터를 요소 수 변경 없이 3D로 변환
(3) (2)에서 저장된 데이터의 2개 차원 변경한 3D로 변환
(4) (2)에서 저장된 데이터의 3개 차원 모두 변경한 3D로 변환

In [ ]:
c1 = [1,2,3,4,5,6,7,8,9,0]
c2 = torch.tensor(c1)
c2

In [ ]:
torch.unsqueeze(c2, 1)
torch.transpose()
torch.permute()

11. 아래 조건에 맞도록 코드를 작성하세요.

11. 아래 조건에 맞도록 코드를 작성하세요.
데이터
- 국어 90, 70, 80
- 영어 70, 100, 80
- 수학 99, 88, 77
(1) 위에 데이터를 저장
(2) 과목별 합계, 평균, 최고점수 출력
(3) 한 사람의 국어, 영어, 수학 점수 합계, 평균, 최고점수 출력


In [ ]:
e1 = torch.tensor([[90, 70, 80], [70,100,80],[99,88,77]])
print('(1)', torch.max(e1[0]), torch.max(e1[1]), torch.max(e1[2]))

In [137]:
print('(2)')
for i in range(3):
    print(torch.sum(e1[i]), torch.max(e1[i]))

(2)
tensor(240) tensor(90)
tensor(250) tensor(100)
tensor(264) tensor(99)


In [138]:
print('(3)')
torch.sum(e1), torch.max(e1)

(3)


(tensor(754), tensor(100))

12. 아래 조건에 맞도록 코드를 작성하세요.

데이터 1
- 국어 90, 70, 80
- 영어 70, 100, 80
- 수학 99, 88, 77

데이터 2
- 05, 02, 0.7

(1) 위에 데이터를 저장
(2) 데이터1과 데이터2의 사칙연산 결과
(3) 데이터1과 데이터2의 행렬곱셈

In [163]:
m1 = torch.tensor([[90,70,80], [70,100,80], [99,88,77]], dtype=torch.float32)
m2 = torch.tensor([0.5, 0.2, 0.7])

In [164]:
m1.add(m2)

tensor([[ 90.5000,  70.2000,  80.7000],
        [ 70.5000, 100.2000,  80.7000],
        [ 99.5000,  88.2000,  77.7000]])

In [165]:
m1.sub(m2)

tensor([[89.5000, 69.8000, 79.3000],
        [69.5000, 99.8000, 79.3000],
        [98.5000, 87.8000, 76.3000]])

In [166]:
m1.mul(m2)

tensor([[45.0000, 14.0000, 56.0000],
        [35.0000, 20.0000, 56.0000],
        [49.5000, 17.6000, 53.9000]])

In [167]:
m1.div(m2)

tensor([[180.0000, 350.0000, 114.2857],
        [140.0000, 500.0000, 114.2857],
        [198.0000, 440.0000, 110.0000]])

In [169]:
# m1.dtype=torch.float32
m1.matmul(m2)

tensor([115., 111., 121.])

In [171]:
m1.float()


NameError: name 'dtype' is not defined