In [2]:
### ===> 모듈 로딩
import cv2
import numpy as np
##%% md
## [1] 이미지 데이터 로딩 <hr>
### 컬러 / 회색이미지 변환 로딩 가능함
##%%
file='../data/img/han1.png'
##%%
### => 컬러 이미지 로딩 [기본값]
img_rgb=cv2.imread(file, cv2.IMREAD_COLOR)

### => 회색 이미지 로딩
img_gray=cv2.imread(file, cv2.IMREAD_GRAYSCALE)
##%%
### => 이미지 데이터 정보확인
print(f'[Color IMAGE]')
print(f'SHAPE : {img_rgb.shape}     DIM : {img_rgb.ndim}차원', end='  ')
print(f'DTYPE : {img_rgb.dtype}     SIZE : {img_rgb.size}바이트')
##%%
### => 이미지 데이터 정보확인
print(f'[Gray IMAGE]')
print(f'SHAPE : {img_gray.shape}     DIM : {img_gray.ndim}차원', end='  ')
print(f'DTYPE : {img_gray.dtype}     SIZE : {img_gray.size}바이트')
##%%
### => 이미지 창 띄우기
# cv2.imshow('Color Image', img_rgb)

# ### => 이미지 창 제어
# cv2.waitKey(0)

# ### => 이미지 창 닫기
# cv2.destroyWindow('Color Image')
# cv2.waitKey(0)
# cv2.waitKey(0)
# cv2.waitKey(0)
# cv2.waitKey(0)
# cv2.waitKey(0)

[Color IMAGE]
SHAPE : (484, 418, 3)     DIM : 3차원  DTYPE : uint8     SIZE : 606936바이트
[Gray IMAGE]
SHAPE : (484, 418)     DIM : 2차원  DTYPE : uint8     SIZE : 202312바이트


In [2]:
img_file = '../data/img/cha1.jpeg'
img =cv2.imread(img_file)

if img is not None:
    cv2.imshow('cha', img)
    cv2.waitKey()
    cv2.destroyAllWindows()
    cv2.waitKey()
    cv2.waitKey()
    cv2.waitKey()
    cv2.waitKey()
    cv2.waitKey()
else:
    print('No image file!!!')


In [3]:
if img is not None:
    cv2.imshow('cha',img)
    while True:
        key=cv2.waitKey()
        print(f'key=>{key}-{hex(key)}')

        if key==27:
            cv2.destroyAllWindows()
            cv2.waitKey()
            cv2.waitKey()
            cv2.waitKey()

            break
else:
    print('No image file!!')

key=>27-0x1b


In [4]:
img_file = '../data/img/han2.png'
img_gray = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

save_filename = '../data/img/han22.jpeg'
gray_file = cv2.imwrite(save_filename, img_gray)

In [5]:
import time 

img_file = '../data/img/han3.jpg.png'
img = cv2.imread(img_file)

img_b, img_g, img_r = cv2.split(img)

cv2.imshow('[Blue Channel]', img_b)
time.sleep(1)
cv2.imshow('[Green Channel]', img_g)
time.sleep(1)
cv2.imshow('[Red Channel]', img_r)

cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey()
cv2.waitKey()
cv2.waitKey()
cv2.waitKey()
cv2.waitKey()


-1

In [4]:
img_file = '../data/img/han4.png'
img = cv2.imread(img_file)

b, g, r = img[:,:,0], img[:,:,1], img[:,:,2]

cv2.imshow('b', b)
cv2.imshow('g', g)
cv2.imshow('r',r)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey()
cv2.waitKey()
cv2.waitKey()
cv2.waitKey()
cv2.waitKey()


In [3]:
img_file = '../data/img/han4.png'
img = cv2.imread(img_file)

b, g, r = img[:,:,0], img[:,:,1], img[:,:,2]


img_b, img_g, img_r = cv2.split(img)

img_rgb = cv2.merge((img_r, img_g, img_b))

cv2.imshow('[RGB IMAGE]', img_rgb)

cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
import cv2
import numpy as np

img_file = '../data/img/han2.png'
img = cv2.imread(img_file)

src_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
planes = cv2.split(src_hsv)

cv2.imshow('[HSV IMG]', src_hsv)

cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import cv2
import time
import sys
import numpy as np

img_file = '../data/img/han1.png' # 이미지 경로
img = cv2.imread(img_file) # 이미지 로딩
down_img = cv2.resize(img, dsize=(30, 30), interpolation=cv2.INTER_AREA)
up_img = cv2.resize(img, dsize=(0, 0), fx=1.5, fy=1.5, interpolation=cv2.INTER_CUBIC)

# cv2.imshow( "down_img", down_img )
# cv2.imshow( "up_img", up_img )
# cv2.imshow('ORG', img)
# time.sleep(1)
# cv2.destroyAllWindows()
# cv2.waitKey(1)
# cv2.waitKey(1)
# cv2.waitKey(1)
# cv2.waitKey(1)
 

In [3]:
## 도화지 만들기

img = np.zeros((300,300), dtype=np.uint8)
img_w = np.full((300,300),255, dtype=np.uint8)
ret = cv2.imwrite('../data/img/blank.jpg', img_w)
ret

img.shape, img.ndim

((300, 300), 2)

In [4]:
cv2.line(img, (10,10), (70,70), (255,0,0))
print(img)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
cv2.imshow('img',img)
cv2.imshow('img_w',img_w)

# cv2.destroyWindow('img')
# cv2.destroyWindow('img_w')


In [6]:
cv2.line(img,(50,50),(150,50),(255,0,0))
cv2.line(img,(200,50),(300,50),(0,255,0))
cv2.line(img,(350,50),(450,50),(0,0,255))
cv2.line(img, (100,100),(400,100), (255,255,0),10)
cv2.line(img,(100,150),(400,150),(255,0,255),10)
cv2.line(img, (100, 200), (400, 200), (0,255,255), 10)          
cv2.line(img, (100, 250), (400, 250), (200,200,200), 10)        
cv2.line(img, (100, 300), (400, 300), (0,0,0), 10)                    

cv2.line(img, (100, 350), (400, 400), (0,0,255), 20, cv2.LINE_4)   
cv2.line(img, (100, 400), (400, 450), (0,0,255), 20, cv2.LINE_8)    
cv2.line(img, (100, 450), (400, 500), (0,0,255), 20, cv2.LINE_AA)   
cv2.line(img, (0,0), (500,500), (0,0,255))     
cv2.imshow('line', img)
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)


-1

In [2]:
#사진용

frontalface_model = '../data/haarcascades/haarcascade_frontalface_alt.xml'
img_file = '../data/img/cha1.jpeg'


face_detector = cv2.CascadeClassifier(frontalface_model)

imgNP = cv2.imread(img_file)

face_detections = face_detector.detectMultiScale(imgNP)
print(f'** face_detictions RESULT\n{face_detections}')

for (x,y,w,h) in face_detections:
    cv2.rectangle(imgNP,(x,y),(x+w,y+h),(0,255,0),2)

cv2.imshow('[M]',imgNP)
cv2.waitKey(1)
cv2.destroyAllWindows()
cv2.waitKey(1)

** face_detictions RESULT
[[46 34 80 80]]


-1

[ WARN:0@625.898] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/videoio/src/cap_gstreamer.cpp (2386) handleMessage OpenCV | GStreamer warning: your GStreamer installation is missing a required plugin
[ WARN:0@625.898] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/videoio/src/cap_gstreamer.cpp (2402) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module uridecodebin5 reported: Your GStreamer installation is missing a plug-in.
[ WARN:0@625.898] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@625.898] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/video

비디오 프레임을 읽을 수 없습니다.
** face_detictions RESULT
()


In [3]:
# 영상용

frontalface_model = '../data/haarcascades/haarcascade_frontalface_alt.xml'
video_file = '../data/video/1234.mp4'

face_detector = cv2.CascadeClassifier(frontalface_model)
camera = cv2.VideoCapture(video_file)

if not camera.isOpened():
    print("비디오 파일을 열 수 없습니다.")
    exit()

while True:
    # 비디오 프레임 읽기
    ret, frame = camera.read()

    if not ret:
        print("비디오 프레임을 읽을 수 없습니다.")
        break

    # 얼굴 검출
    face_detections = face_detector.detectMultiScale(frame)

    # 검출된 얼굴에 사각형 그리기
    for (x, y, w, h) in face_detections:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # 프레임 화면에 표시
    cv2.imshow('Face Detection', frame) 

    # 'q' 키를 누르면 종료
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 리소스 해제
camera.release()
cv2.destroyAllWindows()

[ WARN:0@24.421] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/videoio/src/cap_gstreamer.cpp (2386) handleMessage OpenCV | GStreamer warning: your GStreamer installation is missing a required plugin
[ WARN:0@24.421] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/videoio/src/cap_gstreamer.cpp (2402) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module uridecodebin0 reported: Your GStreamer installation is missing a plug-in.
[ WARN:0@24.422] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@24.422] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/videoio/s

비디오 프레임을 읽을 수 없습니다.


In [8]:
# 웹캠용

import cv2
import time
import sys
import numpy as np

frontalface_model = '../data/haarcascades/haarcascade_frontalface_alt.xml'
video_file = '../data/video/1234.mp4'

face_detector = cv2.CascadeClassifier(frontalface_model)
camera = cv2.VideoCapture(0)

if not camera.isOpened():
    print("비디오 파일을 열 수 없습니다.")
    exit()

while True:
    # 비디오 프레임 읽기
    ret, frame = camera.read()

    if not ret:
        print("비디오 프레임을 읽을 수 없습니다.")
        break

    # 얼굴 검출
    face_detections = face_detector.detectMultiScale(frame)
    
    # 검출된 얼굴에 사각형 그리기
    for (x, y, w, h) in face_detections:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # 프레임 화면에 표시
    cv2.imshow('Face Detection', frame) 

    # 'q' 키를 누르면 종료
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 리소스 해제
camera.release()
cv2.destroyAllWindows()

[ WARN:0@390.432] global /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_11nitadzeg/croot/opencv-suite_1691620374638/work/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
