## 행렬 곱셈
- 피쳐와 가중치 연산에 활용
- tensor.matmul()


In [2]:
# 모듈 로딩
import torch
import mlx

In [3]:
data = torch.tensor([[1,2], [3,4]])
w=torch.tensor([7])

In [5]:
print(f'data.shape => {data.shape}')
print(f'w.shape => {w.shape}')


data.shape => torch.Size([2, 2])
w.shape => torch.Size([1])


In [7]:
# 원소단위 곱셈 => 인덱스에 1:1 대응하도록 브로드캐스팅
print(f'data.mul(w) => {data.mul(w)}')

data.mul(w) => tensor([[ 7, 14],
        [21, 28]])


In [10]:
# 행열단위 곱셈 => 행x열 : (행, 열) x (원소수, )
# w = torch.tensor([7,8])    1행 2열 x 1행 2열이라 실패함
# print(f'data.matmul(w) => {data.matmul(w)}')

# 행열단위 곱셈 => 행x열 : (행, 열) x (행, 열)
w2 = torch.tensor([[7], [8]]) # 1행 2열 x 2행 1열
print(f'data.matmul(w2) => {data.matmul(w2)}')


data.matmul(w2) => tensor([[23],
        [53]])


In [16]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[4,3], [2,1]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print( m1 * m2 )
print( m1.mul( m2 ) )

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 2])
tensor([[4., 6.],
        [6., 4.]])
tensor([[4., 6.],
        [6., 4.]])


In [17]:
m1.matmul(m2)

tensor([[ 8.,  5.],
        [20., 13.]])

In [18]:
m2.matmul(m1)

tensor([[13., 20.],
        [ 5.,  8.]])

In [20]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
m1.matmul(m2)

tensor([[11.]])

In [21]:
m2.matmul(m1)

tensor([[3., 6.],
        [4., 8.]])

element-wise
[a,b] mul [c] = [a*c, b*c]
[a,b] mul [c,d] = [a*c, b*d]
[a,b] mul [[c],[d]] = [[a*c, b*c],[a*d, b*d]]


matrix-wise
[a,b] matmul [[c],[d]] = [[a*c+b*d]]
[[a],[b]] matmul [c,d] = [[a*c,a*d], [b*c,b*d]]


