## 텐서 연결 & 결합

In [1]:
import pandas as pd
# 모듈 로딩
import torch

In [26]:
# 텐서 데이터 생성
torch.manual_seed(12)

# 임의의 0<=x<1의 실수
X=torch.rand(2,10)
# 0<= x < 2 범위의 임의의 정수
y=torch.randint(0,2,(10,))
y2=torch.randint(0,2,(2,10))


In [27]:
print(f'X => {X.shape}, {X.ndim}D')
print(f'y => {y.shape}, {y.ndim}D')
print(f'y2 => {y2.shape}, {y2.ndim}D')


X => torch.Size([2, 10]), 2D
y => torch.Size([10]), 1D
y2 => torch.Size([2, 10]), 2D


In [31]:
# tensor 연결 cat([텐서1, 텐서2, ...])
xy1 = torch.cat([X,y2], dim=1)
torch.cat([X,y2], dim=0)
print(f'xy1 => {xy1.shape}, {xy1.ndim}D')


xy1 => torch.Size([2, 20]), 2D


In [32]:
print(y2)
print(X)

tensor([[1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0]])
tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456]])


In [34]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [35]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max()) # Returns one value: max
print(t.max(dim=0)) # Returns two values: max and argmax

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [41]:
xy1.max(dim=1)

torch.return_types.max(
values=tensor([1., 1.]),
indices=tensor([10, 12]))

In [38]:
max_value = xy1.max(dim=1)[0]
max_value

tensor([1., 1.])

In [40]:
max_index = xy1.max(dim=1)[1]
max_index

tensor([10, 12])

In [45]:
# 열 단위로 최대값 및 최대값의 인덱스
import pandas as pd
data = pd.DataFrame({'A':[10,11], 'B':[20,22], 'C':[30,33]})
data

A   B   C
0  10  20  30
1  11  22  33

In [49]:
data.max() # 디폴트가 0

A    11
B    22
C    33
dtype: int64

In [50]:
data.max(axis=0)

A    11
B    22
C    33
dtype: int64

In [51]:
data.max(axis=1)

0    30
1    33
dtype: int64

## Tensor 차원/형태 변경

In [54]:
t1 = torch.tensor([[[1,2],[11,22],[44,55]]])
print(f't1 => {t1.shape}, {t1.ndim}D')

t1 => torch.Size([1, 3, 2]), 3D


In [57]:
# 2개의 차원을 변경하는 메서드
t11 = t1.transpose(0,2) # 0번째의 1과 2번째의 2를 자리 바꿈, transpose는 두개만 가능
print(f't11 => {t11.shape}, {t11.ndim}D')


t11 => torch.Size([2, 3, 1]), 3D


In [58]:
# 2개의 차원을 변경하는 메서드
t22 = t1.permute(1,2,0) # 1번째의 3, 2번째의 1, 0번째의 2 순서대로 배치 하라
print(f't22 => {t22.shape}, {t22.ndim}D')


t22 => torch.Size([3, 2, 1]), 3D


In [59]:
t1[None].shape # 텐서플로는 비정형 데이터를 None으로 표기 가능

torch.Size([1, 1, 3, 2])