### 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태

- 모듈로딩


In [67]:
import torch

- Tensor 속성 관련 함수

In [68]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def print_attribute(tensor, name):
    print(f'[Tensor {name}\'s Attribute ]')
    print(f' - tensor.shape : {tensor.shape}')
    print(f' - tensor.ndim : {tensor.ndim}D')
    print(f' - tensor.dtype : {tensor.dtype}')
    print(f' - tensor.device : {tensor.device}')
    print(f' - tensor.requires_grad : {tensor.requires_grad}')
    print(f' - tensor.data \n {tensor.data}')


- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    - 타입별 텐서 클래스 생성자 활용
    - 예) IntTensor(), FloatTensor(), BoolTensor()

In [69]:
# 정수 타입 텐서 생성
t1 = torch.IntTensor(10)
t2 = torch.IntTensor([10.,20.]) # 실수를 정수로 바꿀 때는 데이터 손실 있으므로 경고가 뜨는 것
t3 = torch.BoolTensor([1,1,0,-1])
t4 = torch.FloatTensor([10,20])

print_attribute(t1, 't1')
print_attribute(t2, 't2')
print_attribute(t3, 't3')
print_attribute(t4, 't4')


[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
[Tensor t2's Attribute ]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([10, 20], dtype=torch.int32)
[Tensor t3's Attribute ]
 - tensor.shape : torch.Size([4])
 - tensor.ndim : 1D
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([ True,  True, False,  True])
[Tensor t4's Attribute ]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([10., 20.])


/var/folders/9y/lpn0hjmn5csct06t4_r5qtjr0000gn/T/ipykernel_4889/600922394.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t2 = torch.IntTensor([10.,20.]) # 실수를 정수로 바꿀 때는 데이터 손실 있으므로 경고가 뜨는 것


- Tensor 생성(2) 원하는 값으로 텐서 생성 => torch.tensor()

In [70]:
t1 = torch.tensor(10)       # scalar 데이터, int64
t2 = torch.tensor(10.)      # scalar 데이터, 왜 안 float32..

In [71]:
print_attribute(t1,'t1')
print_attribute(t2, 't2')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 10
[Tensor t2's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 10.0


In [72]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능
t1 = torch.tensor(10., dtype=torch.int32) # scalar 데이터 int32
print_attribute(t1,'t1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 10


/var/folders/9y/lpn0hjmn5csct06t4_r5qtjr0000gn/T/ipykernel_4889/4157645560.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t1 = torch.tensor(10., dtype=torch.int32) # scalar 데이터 int32


In [73]:
t1 = torch.tensor(10., dtype=torch.bool) # scalar 데이터 bool
print_attribute(t1,'t1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 True


In [74]:
t1 = torch.tensor([1,2,3], dtype=torch.int8)        # 2D 데이터
print_attribute(t1, 't1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([3])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([1, 2, 3], dtype=torch.int8)


- Tensor 생성 (3) 특정 값으로 채운 텐서 => 0,1 등의 값

In [75]:
# 0으로 채운 텐서
t1 = torch.zeros(5)         #  tensor([0., 0., 0., 0., 0.])
print_attribute(t1,'t1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([5])
 - tensor.ndim : 1D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([0., 0., 0., 0., 0.])


In [76]:
t1 = torch.zeros((5,5), dtype=torch.int8)     
print_attribute(t1,'t1')
 # tensor([[0., 0., 0., 0., 0.],
 #        [0., 0., 0., 0., 0.],
 #        [0., 0., 0., 0., 0.],
 #        [0., 0., 0., 0., 0.],
 #        [0., 0., 0., 0., 0.]])

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)


In [77]:
t1 = torch.ones((2,4), dtype=torch.int8)     
print_attribute(t1,'t1')
 # tensor([[1, 1, 1, 1],
 #        [1, 1, 1, 1]], dtype=torch.int8)

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([2, 4])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)


In [78]:
# 이미 존재하는 텐서와 동일한 shape으로 값 채우기 => zeros_like(), ones_like()
img = torch.tensor([[2,3,4,5,6,7], [2,3,4,5,6,7]])
print(img.shape)       # torch.Size([2, 6])

torch.Size([2, 6])


In [79]:
zero_image = torch.zeros_like(img)
zero_image
# tensor([[0, 0, 0, 0, 0, 0],
#         [0, 0, 0, 0, 0, 0]])

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

In [80]:
one_imag = torch.ones_like(img)
one_imag
# tensor([[1, 1, 1, 1, 1, 1],
#         [1, 1, 1, 1, 1, 1]])

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])

In [81]:
full_img = torch.full_like(img, 7)
print(full_img)
# tensor([[7, 7, 7, 7, 7, 7],
#         [7, 7, 7, 7, 7, 7]])

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])


In [82]:
# 대각선 방향으로 1 채우기 => eye()
t1 = torch.eye(5)
t1
# tensor([[1., 0., 0., 0., 0.],
#         [0., 1., 0., 0., 0.],
#         [0., 0., 1., 0., 0.],
#         [0., 0., 0., 1., 0.],
#         [0., 0., 0., 0., 1.]])

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [83]:
t1 = torch.eye(2,4)
t1

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.]])

- Tensor 생성 방법 (4) : 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()

In [84]:
torch.manual_seed(12)

t5 = torch.rand(2,3)
t6 = torch.randn(2,3)
t7 = torch.randint(low=1,high=10, size=(2,3))

In [85]:
t5

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])

In [86]:
t6

tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])

In [87]:
t7

tensor([[8, 4, 6],
        [2, 2, 2]])

- Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), torch.tensor()

In [88]:
# 데이터 생성
import numpy as np

data = np.array([11,22,33])
print(data, type(data))

[11 22 33] <class 'numpy.ndarray'>


In [89]:
t1 = torch.from_numpy(data)
t1

tensor([11, 22, 33])

In [90]:
t2 = torch.as_tensor(data)
t2

tensor([11, 22, 33])

In [91]:
t3 = torch.tensor(data)
t3

tensor([11, 22, 33])

In [92]:
# ndarray 원소 변경
data[0]=100

# from_numpy(), as_tensor() ==> 데이터 공유
print(data, t1, t2, t3, sep='\n')

# tensor() ==> 복사본 생성

[100  22  33]
tensor([100,  22,  33])
tensor([100,  22,  33])
tensor([11, 22, 33])
