## Tensor shape 변경
- reshape(), view() : 원소 갯수가 유지됨!, 기존 텐서 공유함

In [1]:
# 모듈 로딩
import torch

In [5]:
# 텐서 데이터 생성
t1 = torch.tensor([[1,2,3], [4,5,6]])

print(t1.shape, t1.ndim)
print(t1)

torch.Size([2, 3]) 2
tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
# [2,3] ==> [3,2] 형태 변경 : 원소 수 동일 6개
t1.view(3,2) # 읽는 갯수를 조절함, 원본 안 바뀜

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
# [2,3] ==> [3,2] 형태 변경 : 원소 수 동일 6개
t1.view(6,1) # 읽는 갯수를 조절함

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [10]:
t1.view(-1,1) # -1은 원소의 갯수 보고 알아서 지정해라

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [11]:
t1.view(1,-1)

tensor([[1, 2, 3, 4, 5, 6]])

In [14]:
# tensor.reshape()
t1.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
# 원소 수 유지되어야 함 !
t1.reshape(-1,7) # shape '[-1, 7]' is invalid for input of size 6

RuntimeError: shape '[-1, 7]' is invalid for input of size 6

- 전치 : 열 <-> 형 변경

In [19]:
print(t1.shape)
t2=t1.T
print(t2.shape)

torch.Size([2, 3])
torch.Size([3, 2])


In [23]:
t2.view(-1,6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
t1.matmul()

In [13]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
m12= m1.matmul( m2 )
print(m12)
print( m12.shape)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
torch.Size([2, 1])


In [25]:
# view size is not compatible with input tensor's size and stride
# t2.view(-1,6)

In [27]:
t3 = t2.reshape(-1,6)
print(t3, t3.is_contiguous())

tensor([[1, 4, 2, 5, 3, 6]]) True


### 텐서 데이터의 메모리 저장 정보 즉 메타데이터
- 현재 저장 형태, 검색 방향 정보, 시작 정보

In [29]:
t1 = torch.tensor([[1,2,3], [4,5,6]])
print( t1.shape, t1.ndim)
print( f't1.storage() = > {t1.storage()}')
print( f't1.storage_offset() = > {t1.storage_offset()}')
print( f't1.stride() = > {t1.stride()}')
print( f't1.is_contiguous() = > {t1.is_contiguous()}')


torch.Size([2, 3]) 2
t1.storage() = >  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() = > 0
t1.stride() = > (3, 1)
t1.is_contiguous() = > True


In [30]:
t2 =t1.view(-1,2)
print( t1.shape, t1.ndim)
print( f't2.storage() = > {t2.storage()}')
print( f't2.storage_offset() = > {t2.storage_offset()}')
print( f't2.stride() = > {t2.stride()}')
print( f't2.is_contiguous() = > {t2.is_contiguous()}')


torch.Size([2, 3]) 2
t2.storage() = >  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t2.storage_offset() = > 0
t2.stride() = > (2, 1)
t2.is_contiguous() = > True


### 차원 제거/추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim) : 텐서에서 차원이 1인 것 추가

In [38]:
# 데이터 생성
t1=torch.tensor([[1,2],[3,4]])
t2=torch.tensor([[1,2,3,4]])
t3=torch.tensor([[[1,1,4]]])

In [39]:
print(f't1 => {t1.shape}, {t1.ndim}D')
print(f't2 => {t2.shape}, {t2.ndim}D')
print(f't3 => {t3.shape}, {t3.ndim}D')


t1 => torch.Size([2, 2]), 2D
t2 => torch.Size([1, 4]), 2D
t3 => torch.Size([1, 1, 3]), 3D


In [45]:
t11=t1.squeeze()
t22=t2.squeeze()
t33=t3.squeeze()
t44=t3.squeeze(dim=0)


print(f't1 차원 축소 => {t11.shape}, {t11.ndim}D') # 1차원인 것만 전체 제거
print(f't2 차원 축소 => {t22.shape}, {t22.ndim}D') # 1차원인 것만 전체 제거
print(f't3 차원 축소 => {t33.shape}, {t33.ndim}D') # 1차원인 것만 전체 제거
print(f't3 차원 축소 => {t44.shape}, {t44.ndim}D') # dim=0, 0번 차원이 1이면 축소


t1 차원 축소 => torch.Size([2, 2]), 2D
t2 차원 축소 => torch.Size([4]), 1D
t3 차원 축소 => torch.Size([3]), 1D
t3 차원 축소 => torch.Size([1, 3]), 2D


In [52]:
## 원소/요소 수 변경 없이 차원 한 차원 증가 시키기 => torch.unsqueeze()
t1.shape
print(f't1 정보 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}, {t1.stride()}')


t1 정보 => torch.Size([2, 2]), 2D, 5764958720, (2, 1)


In [61]:
t11=t1.unsqueeze(dim=0)
t22=t1.unsqueeze(dim=-1)

print(f't1 => {t1}')
print(f't11 => {t11}')
print(f't22 => {t22}')

print(f't1 0번째 차원 추가 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}, {t11.stride()}')
print(f't1 1번째 차원 추가 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}, {t22.stride()}')


t1 => tensor([[1, 2],
        [3, 4]])
t11 => tensor([[[1, 2],
         [3, 4]]])
t22 => tensor([[[1],
         [2]],

        [[3],
         [4]]])
t1 0번째 차원 추가 => torch.Size([1, 2, 2]), 3D, 5764958720, (4, 2, 1)
t1 1번째 차원 추가 => torch.Size([2, 2, 1]), 3D, 5764958720, (2, 1, 1)
