### 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태


In [2]:
import torch

### 텐서 매개변수
- .shape, .ndim, .dtype, .device, .requires_grad, .data
- .requires_grad 미분 가능 여부
- .data 실제 데이터 보기

In [3]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def print_attribute(tensor, name):
    print(f'[Tensor {name}\'s Attribute ]')
    print(f' - tensor.shape : {tensor.shape}')
    print(f' - tensor.ndim : {tensor.ndim}D')
    print(f' - tensor.dtype : {tensor.dtype}')
    print(f' - tensor.device : {tensor.device}')
    print(f' - tensor.requires_grad : {tensor.requires_grad}')
    print(f' - tensor.data \n {tensor.data}')
t1 = torch.IntTensor(10)
print_attribute(t1, 't1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)


- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    - 타입별 텐서 클래스 생성자 활용
    - 예) IntTensor(), FloatTensor(), BoolTensor()

In [4]:
t1 = torch.IntTensor(10)
t2 = torch.tensor(10.) # 자동으로 타입분류
print_attribute(t1,'t1')
print_attribute(t2, 't2')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
[Tensor t2's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 10.0


- Tensor 생성(2) 원하는 값으로 텐서 생성 => torch.tensor()

In [5]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능
t1 = torch.tensor(10., dtype=torch.int32)
print_attribute(t1,'t1')


[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 10


/var/folders/9y/lpn0hjmn5csct06t4_r5qtjr0000gn/T/ipykernel_34040/728258258.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t1 = torch.tensor(10., dtype=torch.int32)


- Tensor 생성 (3) 특정 값으로 채운 텐서 => 0,1 등의 값
    - .zeros, .ones, .zeros_like(), .ones_like(), .full_like()
    - .zeros_like(), .ones_like() 동일한 크기의 텐서의 값을 전부 0 or 1로 바꿈
    - .full_like(a,b) a 크기와 같은 텐서의 값을 모두 b로 바꿈

In [6]:
t1 = torch.zeros((5,5), dtype=torch.int8)     
print_attribute(t1,'t1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)


- Tensor 생성 방법 (4) : 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()

In [7]:
torch.manual_seed(12)

# 0<= x <1 임의의 실수를 2행 3열 채우기 
t5 = torch.rand(2,3)

# 0<= x <1 임의의 정수를 2행 3열 채우기
t6 = torch.randn(2,3)

# low<= x <high 임의의 정수를 2행 3열 채우기
t7 = torch.randint(low=1,high=10, size=(2,3))

print(t5, t6, t7, sep='\n')

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])
tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])
tensor([[8, 4, 6],
        [2, 2, 2]])


- Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), torch.tensor()
    - .from_numpy() numpy 값 바탕으로 새로 객체 생성
    - .as_tensor() numpy 배열 그대로 공유하며 변환
    - .tensor() numpy 외에도 변환 가능

In [8]:
# 데이터 생성
import numpy as np

data = np.array([11,22,33])
t1 = torch.from_numpy(data)
print(data, type(data))
print(t1)

[11 22 33] <class 'numpy.ndarray'>
tensor([11, 22, 33])


## Tensor 원소/요소 접근
- 인덱싱과 슬라이싱
- 브로드캐스팅 연산


In [9]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
m3 = m1 + m2
print(f' m3.shape =>{m3.shape} \n m3  => {m3}')

 m3.shape =>torch.Size([2, 2]) 
 m3  => tensor([[4., 5.],
        [5., 6.]])


In [10]:
m1.add(m2), m1.sub(m2), m1.mul(m2), m1.div(m2)


(tensor([[4., 5.],
         [5., 6.]]),
 tensor([[-2., -1.],
         [-3., -2.]]),
 tensor([[3., 6.],
         [4., 8.]]),
 tensor([[0.3333, 0.6667],
         [0.2500, 0.5000]]))

## 행렬 곱셈
- 피쳐와 가중치 연산에 활용
- tensor.matmul()


In [11]:
# 원소단위 곱셈 => 인덱스에 1:1 대응하도록 브로드캐스팅
print(f'data.mul(w) => {data.mul(w)}')

AttributeError: 'numpy.ndarray' object has no attribute 'mul'

In [12]:
# 행열단위 곱셈 => 행x열 : (행, 열) x (행, 열)
w2 = torch.tensor([[7], [8]]) # 1행 2열 x 2행 1열
print(f'data.matmul(w2) => {data.matmul(w2)}')

AttributeError: 'numpy.ndarray' object has no attribute 'matmul'

## Tensor shape 변경
- reshape(), view() : 원소 갯수가 유지됨!, 기존 텐서 공유함

In [16]:
t1 = torch.tensor([[1,2,3], [4,5,6]])
t1.view(3,2) # 읽는 갯수를 조절함, 원본 안 바뀜

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [17]:
t1.view(6,1) # 읽는 갯수를 조절함

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [18]:
# tensor.reshape()
t1.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
t2=t1.T
t2.view(-1,6)


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### 텐서 데이터의 메모리 저장 정보 즉 메타데이터
- 현재 저장 형태, 검색 방향 정보, 시작 정보
- .storage(), .storage_offset(), stride(), is_contiguous()

In [21]:
t1 = torch.tensor([[1,2,3], [4,5,6]])
print( t1.shape, t1.ndim)
print( f't1.storage() = > {t1.storage()}')
print( f't1.storage_offset() = > {t1.storage_offset()}')
print( f't1.stride() = > {t1.stride()}')
print( f't1.is_contiguous() = > {t1.is_contiguous()}')


torch.Size([2, 3]) 2
t1.storage() = >  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() = > 0
t1.stride() = > (3, 1)
t1.is_contiguous() = > True


### 차원 제거/추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim) : 텐서에서 차원이 1인 것 추가

In [23]:
# 데이터 생성
t1=torch.tensor([[1,2],[3,4]])
t2=torch.tensor([[1,2,3,4]])
t3=torch.tensor([[[1,1,4]]])

t11=t1.squeeze()
t22=t2.squeeze()
t33=t3.squeeze()
t44=t3.squeeze(dim=0)


print(f't1 차원 축소 => {t11.shape}, {t11.ndim}D') # 1차원인 것만 전체 제거
print(f't2 차원 축소 => {t22.shape}, {t22.ndim}D') # 1차원인 것만 전체 제거
print(f't3 차원 축소 => {t33.shape}, {t33.ndim}D') # 1차원인 것만 전체 제거
print(f't3 차원 축소 => {t44.shape}, {t44.ndim}D') # dim=0, 0번 차원이 1이면 축소


t1 차원 축소 => torch.Size([2, 2]), 2D
t2 차원 축소 => torch.Size([4]), 1D
t3 차원 축소 => torch.Size([3]), 1D
t3 차원 축소 => torch.Size([1, 3]), 2D


In [24]:
## 원소/요소 수 변경 없이 차원 한 차원 증가 시키기 => torch.unsqueeze()
t1.shape
print(f't1 정보 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}, {t1.stride()}')


t1 정보 => torch.Size([2, 2]), 2D, 4386965184, (2, 1)


In [25]:
t11=t1.unsqueeze(dim=0)
t22=t1.unsqueeze(dim=-1)

print(f't1 => {t1}')
print(f't11 => {t11}')
print(f't22 => {t22}')

print(f't1 0번째 차원 추가 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}, {t11.stride()}')
print(f't1 1번째 차원 추가 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}, {t22.stride()}')


t1 => tensor([[1, 2],
        [3, 4]])
t11 => tensor([[[1, 2],
         [3, 4]]])
t22 => tensor([[[1],
         [2]],

        [[3],
         [4]]])
t1 0번째 차원 추가 => torch.Size([1, 2, 2]), 3D, 4386965184, (4, 2, 1)
t1 1번째 차원 추가 => torch.Size([2, 2, 1]), 3D, 4386965184, (2, 1, 1)
