### softmax(), sigmoid() 함수 <hr>
- sigmoid() : y=wx+b 결과   1개 전달 ==> 반환 : 0.0 ~ 1.0 사이 값으로 변환   => 이진분류
- softmax() : y=wx+b 결과 여러개 전달 ==> 반환 : 여러 개의 결과값의 합이 1.0이 되도록 반환  ==> 다중분류

In [1]:
## 모듈 로딩
import torch                            # 파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F         # 파이토치 인공신경망 관련 함수들

In [2]:
# 임의의 데이터 생성
data1 = torch.tensor([1,2,1,1,2])
data1.shape

torch.Size([5])

In [3]:
F.sigmoid(data1)

tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [11]:
import torch.nn as nn

In [12]:
data2 = data1.unsqueeze(dim=0)
F.softmax(data2, dim=1)

RuntimeError: "softmax_lastdim_kernel_impl" not implemented for 'Long'

In [18]:
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)

In [19]:
output

tensor([[0.3360, 0.1907, 0.4732],
        [0.0222, 0.7261, 0.2517]])

In [20]:
output = F.softmax(input)
output

/var/folders/9y/lpn0hjmn5csct06t4_r5qtjr0000gn/T/ipykernel_8461/3683852505.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = F.softmax(input)


tensor([[0.3360, 0.1907, 0.4732],
        [0.0222, 0.7261, 0.2517]])

In [21]:
output.max(dim=1)

torch.return_types.max(
values=tensor([0.4732, 0.7261]),
indices=tensor([2, 1]))

In [24]:
output.max(dim=1)[1][0].item()

2