In [87]:
###

In [88]:
import torch
import torch.nn as nn

class Net(nn.Module):

    # 모델 구성 요소 생성 및 구조 설정 (보통 init은 인스턴스 생성, 추가)
    def __init__(self):                         
        super(Net,self).__init__()      # super().__init__()로 생략 가능
        self.fc1 = nn.Linear(8,4)       # 레이어 이름 변수명이 중요
        self.fc2 = nn.Linear(4,2)
        self.drop = nn.Dropout(0.5)
        self.fc3 = nn.Linear(2,1)

    # 순방향 학습 진행 함수
    def forward(self,x):
        return self.fc3(self.fc2(self.fc1(x)))

In [89]:
### 모델 인스턴스 생성
model = Net()

print(model)

Net(
  (fc1): Linear(in_features=8, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
  (drop): Dropout(p=0.5, inplace=False)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)


In [90]:
### 모델 인스턴스 속성 확인
# 모델의 특정 층 추출
model.fc1

Linear(in_features=8, out_features=4, bias=True)

In [91]:
### 모델 인스턴스 속성 확인
# 모델의 특정 층 추출
model.fc1.weight, model.fc1.bias

(Parameter containing:
 tensor([[-0.1831,  0.3359,  0.1547,  0.1539,  0.2978,  0.3525,  0.1048, -0.2427],
         [-0.2636,  0.3162,  0.1765, -0.2295,  0.0360, -0.1654,  0.1894,  0.0241],
         [-0.2957, -0.2359,  0.2298,  0.3100,  0.1567, -0.0491,  0.1817,  0.1657],
         [-0.0491, -0.3448,  0.0442,  0.3359, -0.2834,  0.3460,  0.1271,  0.2247]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.2253,  0.0677,  0.2431, -0.0352], requires_grad=True))

In [92]:
model.parameters()

<generator object Module.parameters at 0x13adce6d0>

In [93]:
# 모델의 각 층별 w, b 텐서 정보 확인
for m in model.parameters():
    print(m, end='\n\n')

Parameter containing:
tensor([[-0.1831,  0.3359,  0.1547,  0.1539,  0.2978,  0.3525,  0.1048, -0.2427],
        [-0.2636,  0.3162,  0.1765, -0.2295,  0.0360, -0.1654,  0.1894,  0.0241],
        [-0.2957, -0.2359,  0.2298,  0.3100,  0.1567, -0.0491,  0.1817,  0.1657],
        [-0.0491, -0.3448,  0.0442,  0.3359, -0.2834,  0.3460,  0.1271,  0.2247]],
       requires_grad=True)

Parameter containing:
tensor([-0.2253,  0.0677,  0.2431, -0.0352], requires_grad=True)

Parameter containing:
tensor([[ 0.0148, -0.0257, -0.1827, -0.4351],
        [ 0.3956,  0.4034, -0.2282, -0.0105]], requires_grad=True)

Parameter containing:
tensor([0.4659, 0.2439], requires_grad=True)

Parameter containing:
tensor([[0.1136, 0.5879]], requires_grad=True)

Parameter containing:
tensor([-0.4809], requires_grad=True)



In [94]:
# 모델의 각 층별 w, b 텐서 정보 확인 + 이름 포함
for m in model.named_parameters():
    print(m, end='\n\n')

('fc1.weight', Parameter containing:
tensor([[-0.1831,  0.3359,  0.1547,  0.1539,  0.2978,  0.3525,  0.1048, -0.2427],
        [-0.2636,  0.3162,  0.1765, -0.2295,  0.0360, -0.1654,  0.1894,  0.0241],
        [-0.2957, -0.2359,  0.2298,  0.3100,  0.1567, -0.0491,  0.1817,  0.1657],
        [-0.0491, -0.3448,  0.0442,  0.3359, -0.2834,  0.3460,  0.1271,  0.2247]],
       requires_grad=True))

('fc1.bias', Parameter containing:
tensor([-0.2253,  0.0677,  0.2431, -0.0352], requires_grad=True))

('fc2.weight', Parameter containing:
tensor([[ 0.0148, -0.0257, -0.1827, -0.4351],
        [ 0.3956,  0.4034, -0.2282, -0.0105]], requires_grad=True))

('fc2.bias', Parameter containing:
tensor([0.4659, 0.2439], requires_grad=True))

('fc3.weight', Parameter containing:
tensor([[0.1136, 0.5879]], requires_grad=True))

('fc3.bias', Parameter containing:
tensor([-0.4809], requires_grad=True))



- Layer의 가중치 설정

In [95]:
# 세비어 알고리즘의 가중치 초기화 - S자 모형에서 좋음

nn.init.xavier_uniform_(model.fc1.weight)   # _ : inplace = True 의미(저장됨)

Parameter containing:
tensor([[-0.4549,  0.0774, -0.3603, -0.7001, -0.2724,  0.7017, -0.5751,  0.2083],
        [ 0.3311, -0.2439, -0.6362, -0.5138, -0.1863, -0.2128, -0.4619, -0.4450],
        [-0.6114, -0.6620,  0.7016,  0.6546,  0.3998, -0.5668,  0.3344,  0.0197],
        [-0.4307, -0.2502, -0.0700, -0.3887, -0.6610,  0.1265, -0.4456,  0.0408]],
       requires_grad=True)

In [96]:
model.fc1.weight

Parameter containing:
tensor([[-0.4549,  0.0774, -0.3603, -0.7001, -0.2724,  0.7017, -0.5751,  0.2083],
        [ 0.3311, -0.2439, -0.6362, -0.5138, -0.1863, -0.2128, -0.4619, -0.4450],
        [-0.6114, -0.6620,  0.7016,  0.6546,  0.3998, -0.5668,  0.3344,  0.0197],
        [-0.4307, -0.2502, -0.0700, -0.3887, -0.6610,  0.1265, -0.4456,  0.0408]],
       requires_grad=True)

In [97]:
for name, child in model.named_children():
    nn.init.xavier_uniform(child.weight)

/var/folders/9y/lpn0hjmn5csct06t4_r5qtjr0000gn/T/ipykernel_46686/872923808.py:2: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(child.weight)


AttributeError: 'Dropout' object has no attribute 'weight'

In [98]:
# 모델 구성 모든 Layer 가져오기
for child in model.children():
    print(child, end='\n\n')


# 모델 구성 모든 Layer 이름까지 가져오기
for child in model.named_children():
    print(child, end='\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Dropout(p=0.5, inplace=False)

Linear(in_features=2, out_features=1, bias=True)

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('drop', Dropout(p=0.5, inplace=False))

('fc3', Linear(in_features=2, out_features=1, bias=True))



In [99]:
# 헤 알고리즘의 가중치 초기화 (keras에는 he임)
nn.init.kaiming_normal_(model.fc2.weight)

Parameter containing:
tensor([[ 0.0399, -0.2192, -0.1094, -0.2222],
        [ 1.6710,  1.2754, -0.5390, -0.7937]], requires_grad=True)

In [100]:
from torchinfo import summary

summary(model)
#  ( w 8개 x b 1개 ) x feature 4개 = 36
#  ( w 4개 x b 1개 ) x feature 2개 = 10
#  ( w 2개 x b 1개)  x feature 1개 =  3
# 총합 49개

Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Dropout: 1-3                           --
├─Linear: 1-4                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0